### PR TITLE
reworked types, methods now on useStore

### PR DESCRIPTION
**Pull request by funwithtriangles**
So I was reworking the types (#42) which lead me to some other changes (e.g. having `undo`, `redo`, etc, live as static methods (e.g. `useStore.zundo.undo()`)

Not sure if this is the direction you want to go in (or if it clashes with all the stuff you've done with v2) but thought I'd put this up here as a draft.

Currently all stories are broken except for "other middlewares", where you can see the new API

### CODE REVIEW

**Comment by charkour** [comment]
Sweet, thanks for this!

In v2, I went a similar route like this: `useStore.temporal.undo()`. Maybe temporal is the wrong word. What do you think?

My other concern is that this PR introduces breaking API changes, so I could release this as a beta npm package in the interim before v2 is released rather than release v1.7.0. What do you think?

**Comment by funwithtriangles** [comment]
I think `temporal` is okay, but there is a risk of clashing with other libraries because it's isn't as specific as `zundo`.

Totally makes sense to release as a beta version! Let's make sure we're matching on API at least. Is it worth me fixing up the stories, or will these be completely overhauled anyway?

**Comment by charkour** [comment]
Okay, the only other potential clash would be multiple middleware using the same `temporal` name to extend the store? Maybe we could add a user option to allow them to call it whatever they want.

I prefer `temporal` because I thought that was the best word to encapsulate the state tracking idea, both undo and redo. Perhaps there is a better word.

No need to update the stories. They will have a major overhaul. The progress of [v2 can be found on this branch](https://github.com/charkour/zundo/pull/43). I've opted to use TDD instead of storybook to drive the development. Would you want to help cross off some features? I can provide a better description of each bullet point. Right now, they just make sense in my head.

**Comment by funwithtriangles** [comment]
The only other word I can think of is `history`, which is a bit more typical when you're thinking of undo/redo. If it's possible to have an option to change the word in case of clashes, I guess that's the best approach (although I fear typing it might be quite complicated 😅). 

I can take a look at devtools support for v2 (e.g. named actions)

**Comment by funwithtriangles** [comment]
>  I've opted to use TDD instead of storybook to drive the development.

This makes sense but it could be quite nice to have one story/runnable page to test things like Redux devtools. Otherwise it's a bit of a pain to link the library locally to another local repo.

**Comment by charkour** [comment]
I like the word `history`, but feel that it implies only the past and not the future. I like `temporal` because it is a word that mean related to time. 

Thanks for being willing to look at dev tools!

> This makes sense but it could be quite nice to have one story/runnable page to test things like Redux devtools. Otherwise it's a bit of a pain to link the library locally to another local repo.

I don't have storybook set up, but I do have a way to testing the library visually. I'm re-structuring the repo in [v2](https://github.com/charkour/zundo/pull/43), but haven't added storybook back yet. 

Basic ways to test:
- `pnpm i` at root
- `cd packages/zundo` and `pnpm build`
- `cd ../../apps/web` and `pnpm dev`

The apps/web next.js project is similar to storybook where you can visually test it. In the future, the `web` next.js project will become the examples page, but right now, I'm using it for visual testing. 

The branch should be in a working state. I'm working on the history depth limit and am fixing a couple bugs regarding when the store should clear. So sorry the development environment isn't in a good spot yet, so I completely understand if you want to wait. My goal is to have the repo cleaned up by the end of the weekend.

**Comment by charkour** [comment]
With this current PR #44, are you wanting me to release a beta for you to use before v2 is done? Just let me know. Thanks!

**Comment by funwithtriangles** [comment]
Thanks for all this info! Very useful. Currently I am just linking to that branch as a package and so don't really need this as a release (or even this draft PR). I will keep this PR open just in case that fails for some reason. I will close it when all is confirmed and working well.

**Comment by charkour** [comment]
Sounds good. Thanks for the updates and the help.

**Comment by funwithtriangles** [comment]
So actually it might be useful for us if you could publish this PR as a beta. Unfortunately our CI is failing when trying to pull the package from my Github branch, no idea why. It should be known that this branch is definitely a bit of a mess though!

**Comment by charkour** [comment]
Sounds good. Thanks for all the work, @funwithtriangles. I'll give it a review after my work day. Thanks for the patience!

**Review by charkour — APPROVED** [review]
This is looking great. And I'll release a temporary version for you.

I'll wait to merge this in for now.

**Comment by charkour** [comment]
This has been released as [v2.0.0-experimental.0](https://www.npmjs.com/package/zundo/v/2.0.0-experimental.0). Thank you for the help!

You can install with `npm i zundo@experimental`. I'll continue to work on zundo v2 this weekend.

**Comment by funwithtriangles** [comment]
Amazing, thanks!

**Pull request merged**
