### PR TITLE
Cool-off period

### PR DESCRIPTION
**Pull request by funwithtriangles**
- Adds`coolOffDurationMs` to options to allow debouncing of actions
- Using the term "cool-off" instead of "debounce" because I think it's more descriptive. You are setting for how many milliseconds history will be disabled after each change in state

**Important:** Even with this setting disabled, this PR still changes the behaviour of Zundo. Any changes that happen instantly together will only be recorded as a single item in history.

To explain what I mean, take this piece of code:

```javascript
increasePopulation()
increasePopulation()
increasePopulation()
```

Before this PR, 3 items would be added to history and you have to undo 3 times to get back to 0

After this PR (even with `coolOffDurationMs` as `undefined`), only one new item is added to history and one undo is required to get back to 0

The reason this happens is because changes are now wrapped in a `setTimeout`, and even if the duration is set to `undefined`, the `setTimeout` still happens one frame later. Personally I think this is a good feature but can understand why we might want an option to skip the `setTimeout` completely.

### CODE REVIEW

**Comment by charkour** [comment]
Thanks for this! I can check it tomorrow.

**Review by charkour — APPROVED** [review]
I'll try testing this, but if the coolDownDuration is set to 0ms, will the changes that happen instantly together be recorded?

**Comment by charkour** [comment]
I tried it out and seeing the duration to 0ms does not track changes that instantly happen together (it saves 1 state instead of 3). This is alright. In the future, we could add in that feature, but for now this is fine.

**Comment by charkour** [comment]
I am trying to deploy a new version of the package and am getting this error, would you be willing to fix this? 

image

**Comment by funwithtriangles** [comment]
I think 0 ms is basically the same as `undefined`. I will have a look at that type issue!

**Comment by charkour** [comment]
You're right. 0 will behave as `undefined` in this context.

**Pull request merged**
