### PR TITLE
add github action

### PR DESCRIPTION
**Pull request by BrunnerLivio**
:)

### CODE REVIEW

**Comment by charkour** [comment]
Looks cool! What is junit?

**Comment by BrunnerLivio** [comment]
@charkour In general junit is a report of your test cases written in XML which is supported by most test runners.

I added an action which will read that junit file (generated from vitest) and then should display a summary in the PR. It's totally optional though

**Comment by charkour** [comment]
That's awesome! We can give it a go!

Never got around to adding the action back so this will be nice. 

Are the results supposed to add a comment somewhere?

**Comment by BrunnerLivio** [comment]
@charkour hmm seems like it [doesn't have sufficient permissions](https://github.com/charkour/zundo/actions/runs/3887661277/jobs/6638039377#step:8:67) -- maybe because I am on a fork.

It's up to you whether you wanna go after it -- it will be hard from my side to fix this since I am not the repo owner. You can also simply delete that step if it's not useful or too much effort to get it working. I believe the main merit here is that the build/test at least runs through!

**Comment by charkour** [comment]
Awesome, I've added a PAT to this repo. Looks like there might need to be two workflows. One for the test and another to publish the results. The secret is called `JUNIT_PAT`.

Is this something you'd like to work on @BrunnerLivio?

**Comment by BrunnerLivio** [comment]
@charkour I was unfortunately unable to get it working with the report, but at least a more basic pipeline runs through nicely. I also added a matrix build for node v14,v16,18

**Comment by charkour** [comment]
Sounds good! I like the testing matrix. 

The documentation for jUnit isn't super great. But for the commenting to work, it looks there two Workflows need to be run.

**Review by charkour — APPROVED** [review]
Would you be willing to add the `junit.xml` file to the `.gitignore`?

Then I think this is good to go

**Review by charkour — CHANGES_REQUESTED** [review]
oops I meant to request changes for this!

**Comment by BrunnerLivio** [comment]
@charkour Oups, that file was meant to be deleted anyway. Not needed to be added to gitignore since it won't get generated anymore!

**Comment by charkour** [comment]
Thank you!

**Review by charkour — APPROVED** [review]
Will be nice to run tests before merging. Thanks!

**Pull request merged**
