### PR TITLE
Add middleware to temporal store

### PR DESCRIPTION
**Pull request by charkour**
- [x] Add docs
- [x] Add tests?

865 B --> 888 B (increase 23 B)

### CODE REVIEW

**Comment by charkour** [comment]
@SugarF0x, I'm planning on releasing this today. Sorry for the delay on this!

**Comment by charkour** [comment]
Let me know if there are improvements to the documentation I should add. Thanks!

**Comment by SugarF0x** [comment]
looking fire 🔥🔥🔥

**Comment by charkour** [comment]
After a bit of testing, this was finally released in v2.0.0-beta.16. Sorry for the delay. Having a job and then doing open source is difficult.

**Pull request merged**
